---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  namespace: k8s-projet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: pma-configmap
                  key: pma_host 
            - name: PMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: pma-configmap
                  key: pma_port            
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_root_password
            