apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: k8s-projet
spec:
  selector:
    app: mysql 
    tier: wordpress
  type: ClusterIP                     
  ports:
  - port: 3306
    targetPort: 3306