apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: k8s-projet
spec:
  selector:
    app: wp-front
    tier: wordpress
  type: NodePort                      
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
