apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: k8s-projet
  labels:
    app: wp-front
    tier: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-front
      tier: wordpress
  template:
    metadata:
      labels:
        app: wp-front
        tier: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-configmap
              key: host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wp-configmap
              key: user
        - name:  WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: password 
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wp-configmap 
              key: db
      # volumes:
      # - name: data-wordpress
      #   emptyDir:
      #     sizeLimit: 500Mi 
      volumes:
      - name: wordpress-data
        hostPath:
          path: /wordpress-data